### ISSUE TITLE
STATUS_INVALID_PARAMETER: 0xc000000d when reading CSV with pandas

### ISSUE THREAD

**Issue by mattinbits** [jborean93/smbprotocol#112]
I have an issue where, while reading a CSV file with `smbprotocol` using `pandas.read_csv`, I receive the following Exception:

```
Traceback (most recent call last):
  File "/home/matt/code/smb-example-python/smb.py", line 50, in <module>
    df = pd.read_csv(fd)
  File "/home/matt/code/smb-example-python/env/lib/python3.8/site-packages/pandas/io/parsers.py", line 610, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/matt/code/smb-example-python/env/lib/python3.8/site-packages/pandas/io/parsers.py", line 468, in _read
    return parser.read(nrows)
  File "/home/matt/code/smb-example-python/env/lib/python3.8/site-packages/pandas/io/parsers.py", line 1057, in read
    index, columns, col_dict = self._engine.read(nrows)
  File "/home/matt/code/smb-example-python/env/lib/python3.8/site-packages/pandas/io/parsers.py", line 2061, in read
    data = self._reader.read(nrows)
  File "pandas/_libs/parsers.pyx", line 756, in pandas._libs.parsers.TextReader.read
  File "pandas/_libs/parsers.pyx", line 771, in pandas._libs.parsers.TextReader._read_low_memory
  File "pandas/_libs/parsers.pyx", line 827, in pandas._libs.parsers.TextReader._read_rows
  File "pandas/_libs/parsers.pyx", line 814, in pandas._libs.parsers.TextReader._tokenize_rows
  File "pandas/_libs/parsers.pyx", line 1943, in pandas._libs.parsers.raise_parser_error
  File "/home/matt/code/smb-example-python/env/lib/python3.8/site-packages/smbclient/_io.py", line 573, in readinto
    file_bytes = recv_func(request)
  File "/home/matt/code/smb-example-python/env/lib/python3.8/site-packages/smbprotocol/open.py", line 1313, in _read_response
    response = self.connection.receive(request, wait=wait)
  File "/home/matt/code/smb-example-python/env/lib/python3.8/site-packages/smbprotocol/connection.py", line 928, in receive
    raise SMBResponseException(response)
smbprotocol.exceptions.InvalidParameter: Received unexpected status from the server: An invalid parameter was passed to a service or function. (3221225485) STATUS_INVALID_PARAMETER: 0xc000000d
```

This is generated from the following code (sanitised to remove private info):

```
from smbclient import (
    open_file,
    register_session,
)
import pandas as pd

register_session("server", username=username, password=password)

with open_file(r"//server/SHARE/path/to/file.csv") as fd:
    df = pd.read_csv(fd)
    print(df)
```

From debugging, I can see that there are several successful calls to `file_bytes = recv_func(request)` in `readinto()`, where contents of the file are read successfully, and part way through the file read, the exception above occurs.

Some other things I've observed:

- Several other similar CSV files in the same file share can be read successfully. So there appears to be something particular about this file, but I cannot see anything particular at the offset where the error occurs. (I'm afraid I can't share the file).
- If I read the file from a local directory using `pd.read_csv()`, I can read the file successfully.
- If I switch the pandas parser using `pd.read_csv(engine="python") then I can read the file successfully using `smbprotocol`, so there seems to be something about the interaction between the pandas C parser and smbprotocol. 
- If I skip pandas and just do `print(fd.read())` I can read the whole file, which also suggests something about the interaction between the pandas C parser and smbprotocol. 
- At the time of the failure, the `chunksize` is 262145 and the `credit_request` is 5. This is the first time the `credit_request` is greater than 4 in the iterations that precede the failure. 

I realise I'm probably not providing enough information to get a definitive cause. But any advice on how to proceed in debugging this issue would be gratefully received.

**Comment by jborean93** [comment]
I will have to look at bit further into this but I cannot think of a reason for this to occur. If the `readinto` call is working on an offset that's greater than the actual file you would get `STATUS_END_OF_FILE` not `STATUS_INVALID_PARAMETER`. The `smbclient` code isn't even exposing a way to call it with unbuffered reads which is one case where this could cause this status code so I can't see that being the problem.

It's definitely tricky as you have noticed this starts getting into the credit charge logic which is difficult to wrap your head around. A few things that would be great to know is

* The total size of the file
* How many read requests occur and at what offsets + length
* The credit charge for each of these

Looking at the specs for the [server responding to a read request](https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-smb2/21e8b343-34e9-4fca-8d93-03dd2d3e961e) we can see a few scenarios where it is meant to return `STATUS_INVALID_PARAMETER`

* `Length` is greater than `Connection.MaxReadSize`
  * I don't think this is the case as there is [a check](https://github.com/jborean93/smbprotocol/blob/d6d21a0b17973b787b1047b146398f1d50612f72/smbprotocol/open.py#L1276-L1279) for this before it even sends the request
* Credits are in place and the `CreditCharge` is invalid
  * This could be the problem but what makes the `CreditCharge` an invalid value is really up in the air
  * Would have to know more about the total length of the file and the previous credit requests/charges and how many requests have occurred
* An unbuffered read was requested on a named pipe
  * This doesn't apply here as it's not a named pipe and we don't request `SMB2_READFLAG_READ_UNBUFFERED` from `smbclient` in any way
* The `Channel` value is not set to a valid option
  * This doesn't apply here as we set the value to `SMB2_CHANNEL_NONE`

It could also be something else as the MS docs don't always show the full information but the data does seem to point to the credit system being the culprit here.

**Comment by mattinbits** [comment]
Sorry for the delay in replying. I've been able to create a reproducible example on an anonymized file, so it's easier to share what's happening.

Python code:

```
from smbclient import (
    open_file,
    register_session,
)
import pandas as pd

register_session("localhost", username="test", password="pass")

with open_file("//localhost/public/records.csv") as fd:
    df = pd.read_csv(fd)
    print(df)
```

I'm using Docker to run SMB:

```
FROM dperson/samba

ENV USER="test;pass" \
    SHARE="public;/tmp"
```

```
docker run -d -p 139:139 -p 445:445 -v $PWD/test_files:/tmp smb
```

Data file:
https://gist.github.com/mattinbits/38df05c4ebbc558d9ccdd013c98c294c

The problem seems to be related to the non-ascii characters that appear periodically. For example if I remove just line 8320, where there is an "ö", the error does not occur. So it maybe that these characters are causing pandas, or some intermediate library used by pandas, to make an invalid call to smbprotocol?

**Comment by mattinbits** [comment]
After doing some debugging on the `read` calls that pandas is making, I can reproduce the error without pandas:

```
with open_file("//localhost/public/records.csv") as fd:
    while True:
        fd.read(262144)
```

**Comment by jborean93** [comment]
Sorry it took so long to get back to this, it turns out the problem here was due to some faulty credit calculation logic which is fixed in https://github.com/jborean93/smbprotocol/pull/128.

Specifically requesting a read with the length of `262145` jumps from 4 to 5 credits but the logic which calculated the credit charge value of the header was incorrect. This causes the client to send a request with a credit charge of 4 and request of 5 causing the problem. By using the correct logic in the header builder things start working again.

**Comment by mattinbits** [comment]
Thank you, it's working perfectly.
