### ISSUE TITLE
Disabled log 

### ISSUE THREAD

**Issue by Gregoryarnal** [jborean93/smbprotocol#115]
Hello, 

It's possible to add a feature to disabled some log with read  method ? 
In my use case that currently take around 10/12 seconds to read a 4Mo file.
without :
`
log.debug(str(read))
`
line 1301 and 
`
 log.debug(str(read_response))
`
line 1314 
 On file Open.py for the read method

i can read the same file on 0.2  second.

Thanks !!

**Comment by adiroiban** [comment]
The standard logger is used.

You can get the reference to the logger and configure it as you want.

For example to disable it you can do something like this :)
```
import logging
logging.getLogger('smbprotocol').setLevel(600)
```

**Comment by Gregoryarnal** [comment]
Hi, Thanks for your answer.

I already put a log filter, but even if the logs are not displayed they are executed and this part takes a lot of time :/

**Comment by jborean93** [comment]
I'm curious how much faster is it by default if the line was just `log.debug(read_response)`? Currently the method will always convert the response to a string which is where the bulk of the time may be but by passing in the object itself it should only be run if logging was enabled.

**Comment by jborean93** [comment]
Looking at the code it seems like you are working with an older version. We have done `str(read_response)` since before `v1.0.2` after https://github.com/jborean93/smbprotocol/pull/25. I've done some more testing and even if I remove the `log.debug` line I cannot see any more performance increases so I'm fairly happy with the current setup.
