### ISSUE TITLE
Connection.receive does not break if wait=False

### ISSUE THREAD

**Issue by kvv81** [jborean93/smbprotocol#12]
https://github.com/jborean93/smbprotocol/blob/9c06fc5ce3eab3ce2fa8abcc55c5323baeecdc89/smbprotocol/connection.py#L1024

If wait=False is passed as the parameter then this condition is always False so receive() function makes infinite loop (if no timeout, or exited after timeout otherwise).
I think that correct condition is as below:

`if status is not None and (not wait or status != NtStatus.STATUS_PENDING):`

**Comment by jborean93** [comment]
It's been a while since I've last delved into that code but I think the current behaviour is correct. The `wait` kwarg is designed to continue waiting after receiving a `STATUS_PENDING` response from the server. If that response is received and `wait=True` is set then it will continue to wait until the request has been processed and the final response has been received. The `timeout` parameter is designed to control how long it waits for, if you set it to 0 then it should do what you are looking for.

**Comment by kvv81** [comment]
I intend to wait for STATUS_PENDING reply packet and return it (without waiting for final STATUS_SUCCESS); still we have to receive SOME reply, I don't want to use any timeout value.
I think 'wait' parameter was designed exactly for that purpose, no?

In case if wait=True + timeout=0 we will have 'try to receive but exit immediately if reply is not received yet' logic which is NOT what I need (in this case we can exit without any reply packet).

Please comment what do we get if wait=False is passed - I still think this is not useful use-case at all.

**Comment by jborean93** [comment]
@kvv81, sorry for the delay on this, I've just opened a PR which I believe solves your issue here. When looking at the [new receive code](https://github.com/jborean93/smbprotocol/blob/42a67e7ac29ef843becbb192bfb0581948918108/smbprotocol/connection.py#L984) it is designed to do the following:

* By default (`wait=True, timeout=None`) it will wait until a non-pending result is received indefinitely
    * If a pending result is received it will continue to wait until the non-pending response arrives
    * This is how it works today
* If you set `wait=False` it will return if a pending result or the final result is received from the server
    * I believe this is the issue you are mentioning here and this new behaviour will allow you to wait until just the pending result arrives
* If you set `timeout`, the whole receive operation will continue to wait until either the response has arrived or the timeout has been reached
    * If the timeout has been reached then an exception is raised
    * The pending vs non-pending is still controlled by the `wait` kwarg
    * If you receive a pending result and `wait=True`, it does not reset the timer. A timeout is calculated based on when receive was first entered to now

Let me know if this is what you are looking for.

**Comment by kvv81** [comment]
Yes, I see that new code has now proper checking for 'wait' flag so it should work as expected.
Migration to new library version and testing may take long time, but I think we can resolve/close this issue already.
Thank you very much for assistance!
