### ISSUE TITLE
Any way of getting the most recently modified files and directories ?

### ISSUE THREAD

**Issue by dathanasiadis** [jborean93/smbprotocol#134]

**Comment by jborean93** [comment]
AFAIK there isn't a builtin way to sort as you request the dir contents so you would have to do this after you've retrieved it all. Essentially

```python
import smbclient

entries = sorted(
    smbclient.scandir(r"\\server\share\dir"),
    key=lambda e: e.stat().st_mtime,
    reverse=True
)
```

That will give you the directory listing that is sorted by `st_mtime` which is the number of seconds since EPOCH (1970-01-01). Have a look at [sorting](https://docs.python.org/3/howto/sorting.html) for more details.
