### ISSUE TITLE
How stable is it - what is a timeline for stable release?

### ISSUE THREAD

**Issue by mmank1024** [jborean93/smbprotocol#198]
Hello,
I've noticed that smbprotocol is still marked as beta in pypi. When are you planning to start stable releases? 
I'd like to use it in prod, but I'm little bit worried about stability.

**Comment by adiroiban** [comment]
Hi,

I am using smbprotocol in a production environment for more than one year.
It works great for me.

I am sure I am not using 100% of the features provided by smbprotocol.

If you care about your production environment, my suggestion is to start using subprotocol in your pre-production environment and see for yourself how stable it is.

Cheers

**Comment by jborean93** [comment]
I've just never gotten around to changing the PyPI markers but this library has had a 1.x.y release since 20190-11. I try to follow semver as best as I can so you shouldn't expect any breaking changes until I do a 2.x.y release. Even then I try not to make any major breaking changes but I cannot guarantee what I don't know. If you are concerned you can put a upper pin on the major version so that when 2.x.y does come out you don't immediately pick it up allowing you to test things out before you actually upgrade.
