### ISSUE TITLE
Enquiry about exception propagation in `transport.py`

### ISSUE THREAD

**Issue by henrygoodman** [jborean93/smbprotocol#271]
https://github.com/jborean93/smbprotocol/blob/master/src/smbprotocol/transport.py

In the `smbprotocol.transport.Tcp.connect` function, a `ValueError` is raised if the Tcp connection times out to the server. 

This seems to propagate all the way up to the top through `smbclient._pool.register_session`, therefore if a server timeout occurs when registering the session, the client has to handle a `ValueError`.

Is there a specific reason this shouldn't be a custom exception (like a subclass of `SMBException`) so that the client doesn't catch more than they handle with this generic exception?

(Apologies if this is a stupid question, I am just running into the use case as per above so determining best approach)

**Comment by jborean93** [comment]
Looks like it was originally added by https://github.com/jborean93/smbprotocol/commit/3b5bd3848efb99a4f33b02c40ad296ae1ca3ea3c, I think at the time I used `ValueError` to catch invalid addresses and just assumed it meant an invalid address was specified hence value error. Unfortunately that turned out to be the wrong choice and we are somewhat stuck with this behaviour for backwards compatibility. So yea as mentioned by @adiroiban not everything is an `SMBException` by default but this particular error should have probably stays an `OSError`.
