### ISSUE TITLE
Unable to authenticate from python smbclient while ok with shell tool smbclient

### ISSUE THREAD

**Issue by FredChap** [jborean93/smbprotocol#28]
Hello Jordan and thanks for this great work.

I'm trying to get some SMB stuff (listing files, checking size...) done from a Linux (Debian 10) server running a python 3.7 service.

While I can get this done with the command line tool **smbclient** through subprocess calls, I would like to do it natively from python with your module.

But I get a STATUS_LOGON_FAILURE and after googling for a while, I can't figure out why since my credentials are OK and the linux client succeeds.

Here is a sample code:
```
import os
import smbclient
SMB_SRV = os.getenv('SMB_SERVER')
SMB_PASS = os.getenv('SMB_PASSWORD')
SMB_USER = os.getenv('SMB_USER') # format is 'DOMAIN/user_id'
sess = smbclient.register_session(SMB_SRV, username=SMB_USER, password=SMB_PASS, connection_timeout=10 )
```
The exception raised is:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.7/site-packages/smbclient/_pool.py", line 113, in register_session
    session.connect()
  File "/usr/local/lib/python3.7/site-packages/smbprotocol/session.py", line 319, in connect
    "%s" % str(errors))
smbprotocol.exceptions.SMBAuthenticationError: Failed to authenticate with server: {'NEGOEX (1.3.6.1.4.1.311.2.2.30)': 'Mech Type 1.3.6.1.4.1.311.2.2.30 is not yet supported',
 'KRB5 (1.2.840.113554.1.2.2)': 'Failed to acquire GSSAPI credential with password: Major (131072): An invalid name was supplied, Minor (2529639136): Configuration file does not specify default realm',
 'KRB5_U2U (1.2.840.113554.1.2.2.3)': 'Mech Type 1.2.840.113554.1.2.2.3 is not yet supported',
 'NTLMSSP (1.3.6.1.4.1.311.2.2.10)': 'Received unexpected status from the server: (3221225581) STATUS_LOGON_FAILURE: 0xc000006d'}
```

Debug log says:
```
Initialising session with username: DOMAIN/user_id
Decoding SPNEGO token containing supported auth mechanisms
Both MS_KRB5 and KRB5 received in the initial SPNGEO token, removing MS_KRB5 to avoid duplication of work
Attempting auth with mech NEGOEX (1.3.6.1.4.1.311.2.2.30)
Failed auth for mech NEGOEX (1.3.6.1.4.1.311.2.2.30): Mech Type 1.3.6.1.4.1.311.2.2.30 is not yet supported
Attempting auth with mech KRB5 (1.2.840.113554.1.2.2)
Setting up GSSAPI Security Context for Kerberos auth
GSSAPI: Acquiring credentials handle
GSSAPI: Acquiring credentials handle for user DOMAIN/user_id with password
Failed auth for mech KRB5 (1.2.840.113554.1.2.2): Failed to acquire GSSAPI credential with password: Major (131072): An invalid name was supplied, Minor (2529639136): Configuration file does not specify default realm
Attempting auth with mech KRB5_U2U (1.2.840.113554.1.2.2.3)
Failed auth for mech KRB5_U2U (1.2.840.113554.1.2.2.3): Mech Type 1.2.840.113554.1.2.2.3 is not yet supported
Attempting auth with mech NTLMSSP (1.3.6.1.4.1.311.2.2.10)
Setting up NTLM Security Context for user DOMAIN/user_id
NTLM: Generating Negotiate message
NTLM: Negotiate message: 4e544c4d5353500001000000329088e2000000002800000000000000280000000601b11d0000000f
Sending SMB2_SESSION_SETUP request message
Failed auth for mech NTLMSSP (1.3.6.1.4.1.311.2.2.10): [Errno 32] Broken pipe
Disconnecting transport connection
Disconnecting DirectTcp socket
```
Inspecting the session object, I do know dialect 3.1.1 is used which is fine because target server is Windows 2016.
The command line which is working is:

> smbclient "//$SMB_SERVER/$SMB_SHARE" -d -k -U "$SMB_USER%$SMB_PASSWORD" -m SMB3 -c 'dir'

Any advise would be appreciated :)
Regards,
Fred.

**Comment by jborean93** [comment]
I'm unsure as to why the NTLM auth is failing, maybe it's due to NTLM being disabled on your server or some other policy with NTLM. In any case it looks like you have GSSAPI available which is 100% what you should be using.

The auth problem with GSSAPI/Kerberos is that you are supplying the username in the Microsoft Netlogon format, `DOMAIN\username`, but GSSAPI relies on the UPN format `username@DOMAIN.COM`. If you do not specify the username in the UPN format, gssapi will just get the default realm specified in your `/etc/krb5.conf` file and append it to the username to make the UPN. If the default realm is not specified then it fails with the error you are getting

> Failed to acquire GSSAPI credential with password: Major (131072): An invalid name was supplied, Minor (2529639136): Configuration file does not specify default realm

In this case the solution for you is to provide the username in the UPN format for your SMB_USER env var.

An alternative option is to get a Kerberos ticket for that credential before running the script with `kinit`. If no credentials are specified when a new session is created for smbclient/smbprotocol then it will use the default Kerberos ticket that has been retrieved. This means you can have a script that contains no credentials at all and just relies on the user who is running it to have retrieved the Kerberos ticket. For example this is what you would have to do;

```
$ kinit username@DOMAIN.COM
.... enter password

$ python smb.py

#smb.py
import smbclient

smbclient.listdir(r'\\server\share\dir')
```

**Comment by FredChap** [comment]
Hello Jordan,

Thanks for your quick and valueable feedback.
I need to check about NTLM with people managing the target server.
However, I could give it a try this morning and it's actually working fine with GSSAPI & UPN format.

Many thanks.
Have a nice day.
