### ISSUE TITLE
scandir is slow when access stat

### ISSUE THREAD

**Issue by darouwan** [jborean93/smbprotocol#288]
My folder includes more than 6000 files,  and need to list them order by last modified time. 
I use the code 
```
file_list = []
for file_info in scandir(fr"\\{self._hostname}\{self._service_name}\{path}"):
        file_list.append((file_info.name, file_info.stat().st_mtime))
```
It costs about 60 seconds. 
But if I remove the  f`ile_info.stat().st_mtime`, it only takes 1 second. 
So it seems be caused by stat(). Anyway to accelerate the stat() or other way to list files order by last modified time

**Comment by adiroiban** [comment]
Instead of calling `stat()` for each member, have you tried to use the alredy exisitng information from SMBDirEntry ?  For exampel `SMBDirEntry.smb_info.last_write_time` ?

You can check the source code here

https://github.com/jborean93/smbprotocol/blob/a951779575efe20b5f5c0385729a3e7d249d52d5/src/smbclient/_os.py#L526-L568

**Comment by jborean93** [comment]
Thanks @adiroiban for sharing that info.

The benefits of using `scandir` is that the act of enumerating the directory gives you the raw information accessible through the `dir_info` attribute. The `stat()` method on the yielded `SMBDirInfo` has the `stat()` method to get some more information not available on the `dir_info` attribute but it involves another network request which is done per file. In this case the `last_write_time` on the `dir_info` should contain the information you need.

**Comment by jborean93** [comment]
Closing per the above.
