### ISSUE TITLE
Question/Support: shutil.copyfile() error

### ISSUE THREAD

**Issue by Breinich** [jborean93/smbprotocol#307]
If the file is opened on the remote server, the shutil.copyfile() function fails due to unable to access the target file, because another process uses that file.

I would expect it to be able to copy the file in readonly mode.

**Comment by jborean93** [comment]
The source open is requested with read share access https://github.com/jborean93/smbprotocol/blob/af78f1a7e55a47f741ca9eb484fb2b208a3e86b2/src/smbclient/shutil.py#L134-L138

It was brought up in https://github.com/jborean93/smbprotocol/issues/258 and the fix has been present since the 1.13.0 release https://github.com/jborean93/smbprotocol/blob/master/CHANGELOG.md#1130---2024-03-21. Keep in mind the process that opened the original file must also have been done in a way where they allow read access. If they've opened the file with write access then `shutil.copyfile()` will not be able to open the handle because it is only allowing other reads and not writes.

**Comment by Breinich** [comment]
I see, likely the issue is that the other process opened it with write access.
