### ISSUE TITLE
Getting issue while disconnecting session

### ISSUE THREAD

**Issue by subodh2691** [jborean93/smbprotocol#42]
I am using below code to authenticate and validate the given credentials for a smb share. For which I am calling connect and if response is received then I am closing the connection. Below is my code:

Code:

```
import smbclient
connection = smbclient.register_session(ip, username, pwd)
Print("Credentials validation for ip %s is Successful", ip)
connection.disconnect(False)
```

Error:

`Server message signature could not be verified: 00000000000000000000000000000000 != 4665675f0932baa153f563aefe36e50b
`

**Comment by jborean93** [comment]
I can't replicate this problem using your code. What's the details on the SMB server, i.e. is it a Windows host, Samba, what's the version?

Also I recommend you avoid the `smbclient.register_session` method. It's pooling the connection and session and because you are disconnecting that session outside the pool you may get some false positives i.e.

```python
import smbclient
connection = smbclient.register_session(ip, username, pwd)
connection = smbclient.register_session(ip, username, 'bad password')
print("Credentials validation for ip %s is Successful", ip)
connection.disconnect(False)
```

That won't fail because once register_session sees the same host and username it just re-uses the existing session for that user. What you should be doing is using the lower level interface like

```python
import uuid
from smbprotocol.connection import Connection
from smbprotocol.session import Session

connection = Connection(uuid.uuid4(), ip)
connection.connect()

try:
    session = Session(connection, username, pwd)
    session.connect()
    session.disconnect()
finally:
    connection.disconnect()
```

**Comment by subodh2691** [comment]
Hello @jborean93 Thanks for your reply. Yes it is a Windows host having version Windows server 2012.
I tried the code which you provided and for that too I am facing similar issue.
Also, is there any way through which we can use this module to work in Linux env.? Like connecting windows smb hosts from linux servers? Or is there any other module or workaround which can be used?

**Comment by jborean93** [comment]
It will be hard to fix without being able to replicate it myself sorry. The exception for this is raised [here](https://github.com/jborean93/smbprotocol/blob/4f7b81bebfa2f681d3ea645d4728c32b35bf5a2c/smbprotocol/connection.py#L1145-L1146) and the signature on the left hand side is the signature returned by the SMB server which in your case is not set (all 0's). So in this case your Windows host is not sending a signature when smbprotocol is expecting one and is trying to validate it.

Where exactly is it failing, is it when it's connecting the session, disconnecting the session, or connection? Once you create the session can you also connect to a tree just fine?

> Also, is there any way through which we can use this module to work in Linux env.?

This module works on Linux just fine, it's the entire reason why I wrote it because I had a need of connecting to a SMB share from a host that couldn't natively do it.

**Comment by jborean93** [comment]
While I don't know 100% for sure I did have to fix up a problem when creating multiple sessions on the same connection when it comes to verifying the signature. These changes made their way into the [v1.1.0 release](https://github.com/jborean93/smbprotocol/releases/tag/v1.1.0). It would be great if you could test this out with a newer release and see if the problem is still there.

If are still having problems please post some more info, running `Get-SmbServerConfiguration` (PowerShell cmdlet) on the SMB server would potentially help figure out what the config is for SMB.
