### ISSUE TITLE
Support for retrieving and modifying file permissions

### ISSUE THREAD

**Issue by vinodc** [jborean93/smbprotocol#52]
Nice work with the library! Do you plan to support retrieving file/folder access control entries, and allowing them to be modified?

**Comment by jborean93** [comment]
You can currently do this, you just need to use the low level API to access the security descriptor functions. I even have an example gist for doing this for a file/folder https://gist.github.com/jborean93/c4d8db1db14297de1c9a268084e89d36.

The same thing applies in the reverse using the `SMB2SetInfoRequest` to set a security descriptor. There are 2 problems with this today

1. There's no easy abstraction for all this, it needs to be manually done
2. This operates on raw SIDs for accounts/groups, you need a separate library to translate the SIDs to an account name and vice versa

I've got no plans on making this any simpler anytime soon unfortunately. It's something that would be nice but I just don't have the time.

**Comment by vinodc** [comment]
Thanks for the quick response! I'll take a look at the gist.

**Comment by Alexinio97** [comment]
Is it possible to retrieve the owner of a certain file or path using your library, I've tried using stat but it returns 0 for st_uid and I had a samba shared folder on linux where I've tested.
Great work with this library!

**Comment by jborean93** [comment]
Yes, it requires the same work as mentioned in https://github.com/jborean93/smbprotocol/issues/52#issuecomment-704513552 and even then the value returned is the raw SID and not a human readable name. It still requires a way to translate that SID into a username which isn't part of the SMB protocol itself.

**Comment by praveen-elastic** [comment]
Hey, @jborean93. Thanks for sharing the example gist for getting the SD of the file. This worked successfully for my Windows Network Drive. However I got an error while using it for a Mac OS smb shared folder: 

`smbprotocol.exceptions.NotSupported: Received unexpected status from the server: The request is not supported. (3221225659) STATUS_NOT_SUPPORTED: 0xc00000bb`
The error is thrown on line 
```
resp = fd.connection.receive(req)
```
That's because the request object `req` has a status 3221225659. (i.e. STATUS_NOT_SUPPORTED)
I tried to debug this and looks like the dialect being used is SMB_3_0_0 in Mac shared drive. I tweaked the code to use other dialects but no luck. It still throws the same error. 

I am not able to get why this does not work as other operations such as create, read, write a file works successfully on both Mac and Windows shared drives.

Can you please confirm if this example works on for Mac OS shares too ?

**Comment by jborean93** [comment]
I would be surprised if it would, I'm unsure how these permissions would surface on a macOS SMB server as this is very much Windows specific. Considering it's returning `STATUS_NOT_SUPPORTED` that's a pretty big indication it doesn't work.

**Comment by jborean93** [comment]
Closing as right now this is not something I am planning on supporting in `smbclient`. The code that would be required to manipulate security descriptors outside of Windows is not trivial to do. It would require work to be able to translate security descriptors to account names and vice versa which requires some sort of RPC connection to a Windows host to perform the translations.

In saying that it is currently possible as mentioned to get and set these values yourself using the low level API. It's just not something I plan on adding to the high level API in `smbclient` right now.
