### ISSUE TITLE
Unable to authenticate to Win box because none of the negotiation mechanisms is supported

### ISSUE THREAD

**Issue by pacmanoth** [jborean93/smbprotocol#7]
In attempting to connect to a remote Windows system, I get the following messages during the negotiation process:

smbprotocol.session  | Failed auth for mech NEGOEX (1.3.6.1.4.1.311.2.2.30): Mech Type 1.3.6.1.4.1.311.2.2.30 is not yet supported
smbprotocol.session  | Failed auth for mech KRB5 (1.2.840.113554.1.2.2): Mech Type 1.2.840.113554.1.2.2 is not yet supported
smbprotocol.session  | Failed auth for mech KRB5_U2U (1.2.840.113554.1.2.2.3): Mech Type 1.2.840.113554.1.2.2.3 is not yet supported
smbprotocol.session  | Failed auth for mech NTLMSSP (1.3.6.1.4.1.311.2.2.10): [WinError 10054] An existing connection was forcibly closed by the remote host

Bottom-line, I expect none of the authentication protocols supported by the remote system are supported by smbprotocol.

Please advise,

Peter

**Comment by pacmanoth** [comment]
Here's another version of the errors:
Failed to authenticate with server: {'NEGOEX (1.3.6.1.4.1.311.2.2.30)': 'Mech Type 1.3.6.1.4.1.311.2.2.30 is not yet supported', 'KRB5 (1.2.840.113554.1.2.2)': 'Mech Type 1.2.840.113554.1.2.2 is not yet supported', 'KRB5_U2U (1.2.840.113554.1.2.2.3)': 'Mech Type 1.2.840.113554.1.2.2.3 is not yet supported', 'NTLMSSP (1.3.6.1.4.1.311.2.2.10)': 'Received unexpected status from the server: (3221225581) STATUS_LOGON_FAILURE: 0xc000006d'}

**Comment by jborean93** [comment]
That tells me that the optional Kerberos libraries are not installed on your Python host and the NTLM fallback authentication failed with `STATUS_LOGON_FAILURE`. Can you share some more details such as;

* the type of account (domain, local)
* whether it is an admin or standard account
* can you log on locally with that account

It would also be good for you to enable the [Audit logon events](https://docs.microsoft.com/en-us/windows/security/threat-protection/auditing/basic-audit-logon-events) logging and see what the Security event log shows for this failed logon. Typically there is a sub code that is shows why the logon failed.

**Comment by pacmanoth** [comment]
Thank you, Jordan, for your help /w this issue!!

Kerberos:  are there any examples of how to use/implement the Kerberos addons.  Note that my product runs on both Windows and Linux systems; is this a problem?  I note in your docs that python-gssapi is not supported on Windows ...but I don't see the same mention in the python-gssapi project.  Have things changed in this regard since you wrote your docs?

Type of Account:  domain account, entered as m-ad-dom\administrator  (note that it works -- we don't get the NTLMSSP error -- if using a "local" account)

Admin or Standard:  Admin

Can I log in locally:  Yes'ish.  It's a VM, and I can log on with RDP using these creds

Audit Logon Events:  (see attached images)
Failure Reason:  %%2313, SubStatus: 0xc000006a
Failure Reason:  %%2304, SubStatus: 0x0

![auth-failure1](https://user-images.githubusercontent.com/42876168/61085256-03edbf00-a3ed-11e9-819a-1eaf4c465d3b.PNG)
![auth-failure2](https://user-images.githubusercontent.com/42876168/61085273-0c45fa00-a3ed-11e9-981f-9b49d8d75201.PNG)
![auth-failure3](https://user-images.githubusercontent.com/42876168/61085281-10721780-a3ed-11e9-83f6-672f31178c5a.PNG)

**Comment by jborean93** [comment]
Thanks for the detailed response, really helps to debug these issues.

> are there any examples of how to use/implement the Kerberos addons

If you need to run on both Windows and Linux hosts unfortunately I haven't implemented SSPI support yet, I've got a [placeholder](https://github.com/jborean93/smbprotocol/blob/master/smbprotocol/session.py#L382) for it but haven't had to time to work on it. TBH if you are running on Windows you should be relying on the builtin Windows SMB client to access the files. It will be a lot faster and stable than this library. You do loose out on things like explicit credential access and the ability to use low level commands but there are other ways around that. If you are still interested in getting Kerberos auth working just for linux let me know and I'll try and help you through the requirements.

I honestly don't think it will be hard to implement as I've done something similar in another library but there just hasn't been a big enough reason to do so. The only part I never looked into is how I would get the session key of an SSPI logon. This key is required for the signing and sealing process used in SMB.

Looking at [this page](https://docs.microsoft.com/en-us/windows/security/threat-protection/auditing/event-4625) which details the 4625 event log we can see that the following error codes are mapped to;

* `0xc000006d` - This is either due to a bad username or authentication information
* `0xc000006a` - User logon with misspelled or bad password

So the event log is saying the password used for your administrator account is incorrect. I'm not sure why that would be the case if the password is correct. You did say that you were using a domain account but the event logs indicate there is no domain component set so it looks like it is trying to authenticate using the builtin administrator account. I can't see anything that looks to be wrong in https://github.com/jborean93/smbprotocol/blob/master/smbprotocol/session.py#L468-L494 and I'm sure I've tested a username in that format before.

Potentially I would try and use the UPN format for the username which is in the format `<username>@<domain fqdn>`. For example say I have a domain `domain.com` the Netlogon format is `DOMAIN\username` whereas the UPN would be `username@domain.com`. The other thing you can do is enable some logging so we can see what the username is set as when it gets to this section. This is a bit more but a simple way would be to add the following to the top of your script.

```
import logging

logger = logging.getLogger('smbprotocol')
logger.setLevel(logging.DEBUG)

file_log = logging.FileHandler('smbprotocol.log')
file_log.setLevel(logging.DEBUG)
logger.addHandler(file_log)
```

There will be a lot of output but near the bottom there should be a message like `Setting up NTLM Security Context for user <username>`. Make sure this user is what you expect it to be. If you wish to share the output you can but it may contain sensitive information so I would scrub it first before sharing it.

**Comment by pacmanoth** [comment]
Thank you!  This sentence was the key "the event logs indicate there is no domain component set."  

When we used PSExec with Python 2, we split out the domain because that's how that library wants it.  When we switched to PAExec and Python 3, we failed to put these two pieces back together.

This is now fixed.  Thanks for your help.

P.S.  We would still love to support Kerberos Authentication Mechanisms in our code (on both Linux and Windows).  Please let me know your timeline for this feature.  And THANKS!

**Comment by jborean93** [comment]
@pacmanoth I decided to spend some time on this and created a PR that adds Kerberos support on Windows. Feel free to try out the PR at anytime https://github.com/jborean93/smbprotocol/pull/10. The only requirement is that you install `pywin32` and that should unlock the ability to use Kerberos.
